- name: MySQL configuration
  hosts: mysql
  become: yes
  tasks:
  - name: install boto3 and botocore
    ansible.builtin.pip: 
      name:
      - boto3
      - botocore
      executable: pip3.9

  - name: Installing MySQL server
    ansible.builtin.package:
      name: mysql
      state: present

  - name: Enable the service
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes